from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_dev_utils.types.datetime import UTCDateTime


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth__user_model",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=127), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ANON", "USER", "MODERATOR", "ADMIN", "OWNER", name="role_enum"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_index(
        "users_managed_accounts_list_idx",
        "auth__user_model",
        ["role", sa.literal_column("lower(username)").label("username_lower"), "username"],
        unique=False,
    )
    op.create_index(
        "users_single_owner_uniq",
        "auth__user_model",
        ["role"],
        unique=True,
        postgresql_where=sa.text("role = 'OWNER'"),
    )
    op.create_index("users_username_idx", "auth__user_model", ["username"], unique=False)
    op.create_index(
        "users_username_lower_uniq",
        "auth__user_model",
        [sa.literal_column("lower(username)").label("username_lower")],
        unique=True,
    )
    op.create_table(
        "auth__auth_session_model",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "expires_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "absolute_expires_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "last_used_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "auth_method", sa.Enum("PASSWORD", name="auth_session_auth_method_enum"), nullable=False
        ),
        sa.Column("user_agent_display", sa.String(length=255), nullable=False),
        sa.Column("user_agent_browser", sa.String(length=63), nullable=False),
        sa.Column("user_agent_os", sa.String(length=63), nullable=False),
        sa.Column(
            "user_agent_device",
            sa.Enum(
                "DESKTOP",
                "MOBILE",
                "TABLET",
                "BOT",
                "UNKNOWN",
                name="auth_session_device_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["username"], ["auth__user_model.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("secret_hash", name="auth_sessions_secret_hash_uniq"),
    )
    op.create_index(
        "auth_sessions_absolute_expiry_idx",
        "auth__auth_session_model",
        ["absolute_expires_at"],
        unique=False,
    )
    op.create_index(
        "auth_sessions_expiry_idx", "auth__auth_session_model", ["expires_at"], unique=False
    )
    op.create_index(
        "auth_sessions_username_lower_active_expiry_idx",
        "auth__auth_session_model",
        [
            sa.literal_column("lower(username)").label("username_lower"),
            "is_revoked",
            "expires_at",
            "absolute_expires_at",
        ],
        unique=False,
    )
    op.create_index(
        "auth_sessions_username_lower_active_last_used_idx",
        "auth__auth_session_model",
        [
            sa.literal_column("lower(username)").label("username_lower"),
            "is_revoked",
            "expires_at",
            "absolute_expires_at",
            sa.literal_column("last_used_at DESC"),
            "id",
        ],
        unique=False,
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "auth_sessions_username_lower_active_last_used_idx", table_name="auth__auth_session_model"
    )
    op.drop_index(
        "auth_sessions_username_lower_active_expiry_idx", table_name="auth__auth_session_model"
    )
    op.drop_index("auth_sessions_expiry_idx", table_name="auth__auth_session_model")
    op.drop_index("auth_sessions_absolute_expiry_idx", table_name="auth__auth_session_model")
    op.drop_table("auth__auth_session_model")
    op.drop_index("users_username_lower_uniq", table_name="auth__user_model")
    op.drop_index("users_username_idx", table_name="auth__user_model")
    op.drop_index(
        "users_single_owner_uniq",
        table_name="auth__user_model",
        postgresql_where=sa.text("role = 'OWNER'"),
    )
    op.drop_index("users_managed_accounts_list_idx", table_name="auth__user_model")
    op.drop_table("auth__user_model")
    for enum_name in ("auth_session_device_type_enum", "auth_session_auth_method_enum", "role_enum"):
        postgresql.ENUM(name=enum_name).drop(op.get_bind())
