from alembic import op
import sqlalchemy as sa


revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth__user_model",
        sa.Column("first_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "auth__user_model",
        sa.Column("last_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "auth__user_model",
        sa.Column("middle_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "auth__user_model",
        sa.Column("gender", sa.Text(), nullable=True),
    )
    op.add_column(
        "auth__user_model", sa.Column("avatar_object_name", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth__user_model", "avatar_object_name")
    op.drop_column("auth__user_model", "gender")
    op.drop_column("auth__user_model", "middle_name")
    op.drop_column("auth__user_model", "last_name")
    op.drop_column("auth__user_model", "first_name")
    # ### end Alembic commands ###
